// src/config/audit-labels.ts
//
// Libellés lisibles du journal d'audit : un agent n'a pas à décoder
// « UPDATE_STATUS » ou « DEMANDE_AGENT ».

/** Action → libellé neutre (colonne « Action » du journal). */
export const AUDIT_ACTION_LABELS: Record<string, string> = {
  LOGIN: 'Connexion',
  LOGIN_ATTEMPT: 'Tentative de connexion échouée',
  LOGOUT: 'Déconnexion',
  REGISTER: 'Inscription',
  CREATE: 'Création',
  CREATE_URGENT: 'Création (urgence)',
  UPDATE: 'Modification',
  UPDATE_STATUS: 'Changement de statut',
  STATUS_CHANGE: 'Changement de statut',
  DELETE: 'Suppression',
  VALIDATE: 'Validation',
  REJECT: 'Rejet',
  SUSPEND: 'Suspension',
  ASSIGN: 'Affectation',
  ASSIGNMENT: 'Affectation',
  ASSIGN_ROLE: 'Attribution de rôle',
  REMOVE_ROLE: 'Retrait de rôle',
  ASSIGN_INUE: 'Attribution d\'un INUE',
  ARCHIVE: 'Archivage',
  CANCEL: 'Annulation',
  COMPLETE: 'Clôture',
  CHECK_IN: 'Arrivée enregistrée',
  SEND: 'Envoi',
  SCHEDULE: 'Programmation',
  DUPLICATE: 'Duplication',
  REORDER: 'Réorganisation',
  RESEND: 'Renvoi',
  UPLOAD: 'Dépôt de document',
  DOWNLOAD: 'Téléchargement',
  VIEW: 'Consultation',
  SHARE: 'Partage',
  COMMENT: 'Commentaire',
  NOTE: 'Note',
  PRINT: 'Impression',
  REPRINT: 'Réimpression',
  EXPORT: 'Export',
  ENROLL: 'Enrôlement',
  PROCESS_REQUEST: 'Traitement d\'une demande d\'agent',
  CHANGE_PASSWORD: 'Changement de mot de passe',
  RESET_PASSWORD: 'Réinitialisation du mot de passe',
  FORGOT_PASSWORD: 'Demande de réinitialisation',
  SWITCH_ROLE: 'Changement de rôle actif',
  SUBMIT_REGISTRATION: 'Envoi du dossier d\'enregistrement',
  READ: 'Lecture',
};

/** Verbe conjugué pour le fil d'activité personnel (« a validé … »). */
export const AUDIT_ACTION_VERBS: Record<string, string> = {
  LOGIN: 'vous êtes connecté(e)',
  LOGOUT: 'vous êtes déconnecté(e)',
  CREATE: 'avez créé',
  UPDATE: 'avez modifié',
  UPDATE_STATUS: 'avez changé le statut de',
  STATUS_CHANGE: 'avez changé le statut de',
  DELETE: 'avez supprimé',
  VALIDATE: 'avez validé',
  REJECT: 'avez rejeté',
  SUSPEND: 'avez suspendu',
  ASSIGN: 'avez affecté',
  ASSIGNMENT: 'avez affecté',
  ASSIGN_INUE: 'avez attribué un INUE à',
  ARCHIVE: 'avez archivé',
  CANCEL: 'avez annulé',
  COMPLETE: 'avez clôturé',
  CHECK_IN: 'avez enregistré l\'arrivée pour',
  SEND: 'avez envoyé',
  UPLOAD: 'avez déposé un document pour',
  DOWNLOAD: 'avez téléchargé',
  VIEW: 'avez consulté',
  SHARE: 'avez partagé',
  COMMENT: 'avez commenté',
  NOTE: 'avez écrit un message sur',
  PRINT: 'avez imprimé',
  EXPORT: 'avez exporté',
  PROCESS_REQUEST: 'avez traité',
};

/** Type d'objet → libellé. */
export const AUDIT_ENTITY_LABELS: Record<string, string> = {
  DEMANDE: 'Demande',
  EXIGENCE: 'Exigence de dossier',
  RENDEZ_VOUS: 'Rendez-vous',
  ETUDIANT: 'Dossier étudiant',
  INUE: 'INUE',
  DOCUMENT: 'Document',
  DOCUMENT_INTERNE: 'Document interne',
  CAMPAGNE: 'Campagne',
  PIECE_JOINTE_CAMPAGNE: 'Pièce jointe de campagne',
  SERVICE: 'Service',
  SOUS_SERVICE: 'Sous-service',
  HORAIRE_SERVICE: 'Horaire de service',
  AGENT: 'Agent',
  AFFECTATION_AGENT: 'Affectation d\'agent',
  DISPONIBILITE_AGENT: 'Disponibilité d\'agent',
  EXCEPTION: 'Exception de planning',
  ROLE: 'Rôle',
  PERMISSION: 'Permission',
  UTILISATEUR: 'Utilisateur',
  USER: 'Utilisateur',
  FIL_MESSAGERIE: 'Conversation',
  MESSAGE: 'Message',
  NOTIFICATION: 'Notification',
  PROFIL: 'Profil',
  DEMANDE_AGENT: 'Demande d\'un agent',
  TICKET_SUPPORT: 'Ticket de support',
  CULTURE_ECHANGE: 'Échange culturel',
  DEMANDE_SUR_PLACE: 'Demande sur place',
  AUTHENTIFICATION: 'Authentification',
  AUDIT: 'Journal d\'audit',
  PAIEMENT: 'Paiement',
  COMMENTAIRE: 'Commentaire',
  NOTE: 'Note',
  SESSION: 'Session',
  SYSTEME: 'Système',
};

export const actionLabel = (action: string): string =>
  AUDIT_ACTION_LABELS[action] ?? action.charAt(0) + action.slice(1).toLowerCase().replace(/_/g, ' ');

export const entityLabel = (entityType: string): string =>
  AUDIT_ENTITY_LABELS[entityType] ?? entityType.charAt(0) + entityType.slice(1).toLowerCase().replace(/_/g, ' ');

export const RESULT_LABELS: Record<string, string> = {
  SUCCESS: 'Réussi',
  ERROR: 'Erreur',
  REJECT: 'Refusé',
  WARNING: 'Avertissement',
};
